### PR TITLE
Fixes and cleanup

### PR DESCRIPTION
**Pull request by reicheratwork**
- Fixed missing includes with TopicTraits
- Fixed generation of member setter functions
- Suppressed a large amount of coverity warnings, which are not critical

### CODE REVIEW

**Comment by reicheratwork** [comment]
@e-hndrks I think this is also something that you have a lot of expertise in, so could you please review this?

**Comment by k0ekk0ek** [comment]
I'll let @e-hndrks decide on the C++ changes.

**Review by k0ekk0ek — APPROVED** [review]
Approved under the condition that @e-hndrks approves the newly introduced macros :+1:

**Review by e-hndrks — APPROVED** [review]
I think you did a great job cleaning up unnecessary code yet staying as close to the original behavior of the spec as possible. That said, the original spec seems to be inconsistent when it comes to using virtual destructors (which aren't needed when all the sub-classes add no state of their own) and so we could clean up even further. I would advice to do that in a separate iteration, which we can then also file as an issue on the OMG specification.

**Pull request merged**
