### PR TITLE
Make cyclonedds-cxx compatible with the changes for IDL in cyclonedds

### LINKED ISSUE #154: cyclonedds-cxx master is not compatible with cyclonedds master
## Required information

**Operating system:**
Ubuntu 18.04 LTS

**Cyclone Version**

  -  cyclonedds - master branch, eclipse-cyclonedds/cyclonedds@b74b2f9c5e009cb025a7aac376792d58ad4700df
   - cyclonedds-cxx - template_streaming , 212146f849f93e5dd5980ce60999e58c8ed17a0e

**Observed result or behaviour:**
Compiling the master of `cyclonedds-cxx` with the master of `cyclonedds` leads to the following compilation error

```sh
/home/sumanth.nirmal/apex_middleware_ws/x86_64/cyclonedds-cxx/src/idlcxx/src/streamers.c:722:44: error: ‘IDL_TRUE’ undeclared (first use in this function); did you mean ‘IDL_TYPE’?
       ((const idl_member_t *)node)->key == IDL_TRUE)
                                            ^~~~~~~~
                                            IDL_TYPE
/home/sumanth.nirmal/apex_middleware_ws/x86_64/cyclonedds-cxx/src/idlcxx/src/streamers.c:722:44: note: each undeclared identifier is reported only once for each function it appears in
/home/sumanth.nirmal/apex_middleware_ws/x86_64/cyclonedds-cxx/src/idlcxx/src/streamers.c: In function ‘process_switch_type_spec’:
/home/sumanth.nirmal/apex_middleware_ws/x86_64/cyclonedds-cxx/src/idlcxx/src/streamers.c:1132:32: error: ‘IDL_TRUE’ undeclared (first use in this function); did you mean ‘IDL_TYPE’?
   if (switch_type_spec->key != IDL_TRUE)
                                ^~~~~~~~
                                IDL_TYPE
/home/sumanth.nirmal/apex_middleware_ws/x86_64/cyclonedds-cxx/src/idlcxx/src/types.c: In function ‘emit_enum’:
/home/sumanth.nirmal/apex_middleware_ws/x86_64/cyclonedds-cxx/src/idlcxx/src/types.c:343:11: error: incompatible types when assigning to type ‘uint32_t {aka unsigned int}’ from type ‘const struct <anonymous>’
     value = enumerator->value;
           ^
src/idlcxx/CMakeFiles/idlcxx.dir/build.make:82: recipe for target 'src/idlcxx/CMakeFiles/idlcxx.dir/src/types.c.o' failed
```

**Expected result or behaviour:**

The master branches of `cyclonedds` and `cyclonedds-cxx` should be compatible and can be compiled without any errors.

**Other Info**

The master on `cyclonedds-cxx` is probably broken because of the changes in this MR https://github.com/eclipse-cyclonedds/cyclonedds/pull/923

### PR DESCRIPTION
**Pull request by sumanth-nirmal**
This PR makes the `cyclonedds-cxx` compatible with the latest `cyclonedds`

Closes #154

### CODE REVIEW

**Comment by sumanth-nirmal** [comment]
@k0ekk0ek and @eboasson The current master of `cyclonedds-cxx` is not usable because it is not compatible with `cyclonedds` core and the CI on `cyclonedds-cxx` fails (because of the `iceoryx` version mismatch). I tried to solve the compatibility issue in this MR and the version mismatch here https://github.com/eclipse-cyclonedds/cyclonedds-cxx/pull/142. 

However, the CI in this MR fails on macOS and I am unable to reason the failure (I am not sure if the failures are because of my changes). Can you please suggest a way on how to merge these to revive the `cyclonedds-cxx` master branch?

**Comment by eboasson** [comment]
The build failure on macOS is because GNU bison 3.8 removed some deprecated things. I did a quick hack to work around it (https://github.com/eclipse-cyclonedds/cyclonedds/pull/949), so I expect that'll get fixed today.

Your fix looks correct to me (though I would prefer to leave the official determination of that to the experts, i.e., @k0ekk0ek and @reicheratwork) but it has the disadvantage of being incompatible with the just-released 0.8.0. As there's no `releases/0.8.x` (nor a 0.8.0 tag) for C++ yet, that is a bit problematic. I expect that can be solved today.

**Review by reicheratwork — APPROVED** [review]
Looks good to me!

**Comment by k0ekk0ek** [comment]
Thanks @sumanth-nirmal! Definitely an oversight on my part. On a side note, if you place something like "fixes xxx" in the commit message the issue will [automatically closed and linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

**Review by k0ekk0ek — APPROVED** [review]

**Comment by k0ekk0ek** [comment]
The build failures on this ticket are related to Iceoryx not being compatible(?) and are definitely not related to the changes.

**Pull request merged**
