### PR TITLE
This pull requests adds a C++ representation for calls like write_cdr/read_cdr to the C++ API.

### PR DESCRIPTION
**Pull request by e-hndrks**

### CODE REVIEW

**Comment by k0ekk0ek** [comment]
This should probably go in before #45? I think I'm fine with the changes, I'd love to see some tests, but it's hard to add them right now, so I trust you verified the work manually(?) If @reicheratwork signs of on these changes, I'm happy to merge them.

**Review by reicheratwork — APPROVED** [review]
Does what it is supposed to, therefore approved.

**Review by reicheratwork — APPROVED** [review]
Looks good to me.

**Comment by e-hndrks** [comment]
@k0ekk0ek: Yes, I modified the HelloWorld example to test both read_cdr and write_cdr. Didn't write such a test for dispose_cdr and unregister_instance_cdr, but the changes wrt write_cdr are trivial.

**Comment by k0ekk0ek** [comment]
Totally slipped my mind :sweat_smile: This is going in :+1:

**Pull request merged**
