### PR TITLE
repair issue #461

### PR DESCRIPTION
**Pull request by ruoruoniao**
except branch idl_is_type_spec(node)

As you say, change a fix way~ @eboasson

### CODE REVIEW

**Comment by eboasson** [comment]
Every time I think I have wrapped my head around `idlc`'s inside well enough to review PRs and do so maintenance on it, it seems to catch me in yet another bit of weirdness. Who would have thought that this runs into an infinite recursion between alternating between `y = x->type_spec` and `x = y->parent` ... I did not anyway.

That means what seemed like the less surprising solution doesn't work and your original proposal is infinitely better, thanks to the absence of infinite recursion. Can you please revive it? I am sorry to have caused you this much trouble.

**Comment by ruoruoniao** [comment]
> Every time I think I have wrapped my head around `idlc`'s inside well enough to review PRs and do so maintenance on it, it seems to catch me in yet another bit of weirdness. Who would have thought that this runs into an infinite recursion between alternating between `y = x->type_spec` and `x = y->parent` ... I did not anyway.
> 
> That means what seemed like the less surprising solution doesn't work and your original proposal is infinitely better, thanks to the absence of infinite recursion. Can you please revive it? I am sorry to have caused you this much trouble.

Sure, I am quite surprised when I found the pipeline return error...I don't have a good solution either, unless we can record the path that the function runs on, and terminate it when it encounters the same node, but that's too strange...

**Review by eboasson — COMMENTED** [review]
I think an over-active auto-formatter decided to interfere with this PR — there is the intended change (`idl_is_optional` → `is_optional`) and there is a whole lot of whitespace changes. Can you please update the PR to not have the whitespace changes? Thanks!

**Comment by ruoruoniao** [comment]
Of course (￣▽￣)"

**Review by eboasson — APPROVED** [review]
Thank you @ruoruoniao ☺️

**Pull request merged**
