### PR TITLE
Include generation of TopicTraits and some more general fixes.

### PR DESCRIPTION
**Pull request by e-hndrks**

### CODE REVIEW

**Comment by k0ekk0ek** [comment]
Thanks @e-hndrks. This PR introduces a couple of warnings that weren't there before though, please correct them first.

**Comment by k0ekk0ek** [comment]
The `CUnit_cpp11Backend_Typedef` test is failing too. Probably forgot to add a `;` somewhere by the looks of it?

**Comment by k0ekk0ek** [comment]
The generated header also seems to be off. Running the result on `HelloWorldData.idl` in the examples directory gives:
```
/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: HelloWorldData.hpp
  Source: HelloWorldData.idl
  Cyclone DDS: v0.7.0

*****************************************************************/
#ifndef DDSCXX_HELLOWORLDDATA_HPP
#define DDSCXX_HELLOWORLDDATA_HPP


#include <string>

namespace HelloWorldData
{
  class Msg
  {
  private:
    int32_t userID_;
    std::string message_;

  public:
    Msg() :
        userID_(0) {}

    explicit Msg(
        int32_t userID,
        const std::string& message) :
            userID_(userID),
            message_(message) {}

    int32_t userID() const { return this->userID_; }
    int32_t& userID() { return this->userID_; }
    void userID(int32_t _val_) { this->userID_ = _val_; }
    const std::string& message() const { return this->message_; }
    std::string& message() { return this->message_; }
    void message(const std::string& _val_) { this->message_ = _val_; }
    void message(std::string&& _val_) { this->message_ = _val_; }

    size_t write_struct(void* data, size_t position) const;
    size_t write_size(size_t offset) const;
    size_t read_struct(const void* data, size_t position);
  };

}

#include "dds/dds.hpp"
#include "org/eclipse/cyclonedds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/DataRepresentation.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org { namespace eclipse { namespace cyclonedds { namespace topic {
template <>
class TopicTraits<::HelloWorldData::Msg>
{
public:
  static ::org::eclipse::cyclonedds::topic::DataRepresentationId_t getDataRepresentationId()
  {
    return ::org::eclipse::cyclonedds::topic::OSPL_REPRESENTATION;
  }

  static ::std::vector<uint8_t> getMetaData()
  {
    return ::std::vector<uint8_t>();
  }

  static ::std::vector<uint8_t> getTypeHash()
  {
    return ::std::vector<uint8_t>();
  }

  static ::std::vector<uint8_t> getExtentions()
  {
    return ::std::vector<uint8_t>();
  }

  static const char *getKeyList()
  {
    return "";
  }

  static const char *getTypeName()
  {
    return "::HelloWorldData::Msg";
  }

  static ddsi_sertopic *getSerTopic(const std::string& topic_name)
  {
    auto *st = new ddscxx_sertopic<::HelloWorldData::Msg>(topic_name.c_str(), getTypeName());
    return static_cast<ddsi_sertopic*>(st);
  }

  static size_t getSampleSize()
  {
    return sizeof(::HelloWorldData::Msg);
  }
}
}}}}

REGISTER_TOPIC_TYPE(::HelloWorldData::Msg)
#endif /* DDSCXX_HELLOWORLDDATA_HPP */
namespace HelloWorldData
{

} //end namespace HelloWorldData

#endif /* DDSCXX_HELLOWORLDDATA_HPP */
```
The last namespace block shouldn't be there. I quick investigation shows the tree only has one module node, so it's very likely the backend walks the tree twice?

**Comment by k0ekk0ek** [comment]
The addition of the extra `#endif` block is caused by the `generate_streamers` function printing to the header file too. The last error seems to be: `error: 'class HelloWorldData::Msg' has no member named 'key'` which indicates type generation is incomplete(?)

**Comment by k0ekk0ek** [comment]
@e-hndrks, some warnings and some failing tests still I'm afraid.

**Comment by e-hndrks** [comment]
Closing this pull request due to an issue where Travis isn't triggering on the updates to this pull request. Will re-open a new pull request for the latest update.

**Pull request closed without merging**
