### PR TITLE
Added Liveliness Automatic convenience function with lease_duration paramter.

### PR DESCRIPTION
**Pull request by Kischy**
Fixes Issue #133

### CODE REVIEW

**Review by eboasson — APPROVED** [review]
Looks good to me, thanks @Kischy !

**Comment by Kischy** [comment]
@eboasson Hmm... why did the documentation fail here?

**Comment by eboasson** [comment]
I'm not quite sure. As far as I can tell your PR is valid C++ and does what it aims to do, and therefore I suspect it is a limitation or bug of `sphinx` or some related part. They're even asking for a bug report!

Anyway, we do rely on the auto-generation of the documentation nowadays and so that needs to be looked into.

**Comment by Kischy** [comment]
Ok, thanks for the explanation.

**Pull request merged**
