### PR TITLE
workaround issues 162 and 252

### PR DESCRIPTION
**Pull request by javiersorianoruiz**
Workaround for the issues #162 and #252

### CODE REVIEW

**Review by eboasson — COMMENTED** [review]
Kinda of seems straightforward and harmless to me (and it works for me locally, too), but for some strange reason now gcc 10 is deeply unhappy (just click through on the CI). Any idea why?

I'd love to simply upgrade the CI to use gcc 11 or 12 (getting a much improved static analyzer as well), but it is probably too early to tell anyone with gcc 10 that now *they* are out of luck ...

It seems such an innocent little detail ...

**Comment by Bit-Seq** [comment]
Hello @eboasson,

After we (@javiersorianoruiz and me) have been testing compiling with gcc 10.3.0 and different branches from cyclonedds and cyclonedds-cxx (master, 0.10.2 and 0.10.1) we have seen that the new compilation problem that you refer, it is related with the GoogleTest version.

With 1.12.1 GoogleTest version compiles correctly and the error appears with the 1.10.0 (version that is being used by CI).

Regards.

**Comment by eboasson** [comment]
> Hello @eboasson,
> 
> After we (@javiersorianoruiz and me) have been testing compiling with gcc 10.3.0 and different branches from cyclonedds and cyclonedds-cxx (master, 0.10.2 and 0.10.1) we have seen that the new compilation problem that you refer, it is related with the GoogleTest version.
> 
> With 1.12.1 GoogleTest version compiles correctly and the error appears with the 1.10.0 (version that is being used by CI).
> 
> Regards.

Thanks for that bit of information!

The only reason we're using GoogleTest 1.10 seems to be because our [conanfile.txt](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/master/conanfile.txt) is pinned to it. I've tried taking master+this PR+this:
```diff
diff --git a/conanfile.txt b/conanfile.txt
index fb211d9d..8e71ff84 100644
--- a/conanfile.txt
+++ b/conanfile.txt
@@ -1,5 +1,5 @@
 [requires]
-gtest/1.10.0
+gtest/1.12.1
 boost/1.78.0
 
 [generators]
```
and with that the CI seems happy again as well.

Would you be willing to add this modification to this PR? That's by far the easiest way to merge it.

Quite apart from the failing builds, there is also a formality standing in the way of merging it: the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php) must be signed for us to merge a PR. The `eclipsefdn/eca` CI step currently says that bit hasn't been done yet. Would you be willing to fill out the ECA?

**Comment by javiersorianoruiz** [comment]
As @eboasson has indicated to me, I have signed the Eclipse Contributor Agreement.

I have also done a new commit and push updating in the connanfile.txt the new version of Google test required to compile successfully the workaround proposed in this pull request.

The commit is https://github.com/eclipse-cyclonedds/cyclonedds-cxx/pull/324/commits/f8333221f438bc413b652c225ff7a6bb482103d3

**Comment by javiersorianoruiz** [comment]
As @eboasson has indicated to me, I have signed the Eclipse Contributor Agreement.

I have also done a new commit and push updating in the connanfile.txt the new version of Google test required to compile successfully the workaround proposed in this pull request.

The commit is https://github.com/eclipse-cyclonedds/cyclonedds-cxx/pull/324/commits/f8333221f438bc413b652c225ff7a6bb482103d3

**Review by eboasson — APPROVED** [review]
Thanks a lot @javiersorianoruiz !

**Pull request merged**
